[toolchain]
anchor_version = "0.30.1"
solana_version = "2.0.17"

[features]
seeds = false
skip-lint = false
[programs.localnet]
bookeeper = "F6NKeaoPbchYnbcJZ5YSAqfMcHuP7GLExTuDK3qmgtgW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests//*.ts"